substitutions:
  name: "kmc-smart-tap-mini"
  friendly_name: "KMC Smart Tap Mini"
  outlet_1_name: "Outlet 1"
  outlet_2_name: "Outlet 2"
  outlet_3_name: "Outlet 3"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

bk72xx:
  board: cb2s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: ""

captive_portal:

switch:
  - platform: gpio
    id: outlet1
    name: ${outlet_1_name}
    pin: P26
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    id: outlet2
    name: ${outlet_2_name}
    pin: P24
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    id: relay3
    name: ${outlet_3_name}
    pin: P6
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: RX1
      mode: INPUT
      inverted: True
    name: "Button"
  
status_led:
  pin:
    number: TX1

