substitutions:
  name: "kmc-smart-tap-mini-1"
  friendly_name: "KMC Smart Tap Mini 1"
  outlet_1_name: "Outlet 1"
  outlet_2_name: "Outlet 2"
  outlet_3_name: "Outlet 3"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false

bk72xx:
  board: cb2s

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: ""

captive_portal:

web_server:
 port: 80
 version: 3

switch:
  - platform: gpio
    id: outlet1
    name: ${outlet_1_name}
    pin: P26
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    id: outlet2
    name: ${outlet_2_name}
    pin: P24
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    id: outlet3
    name: ${outlet_3_name}
    pin: P6
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: top_button
    pin:
      number: RX1
      mode: INPUT
      inverted: True
    name: "Button"
    on_release: 
      then:
        - light.turn_off: light_status
        - if:
            condition:
              - lambda: 'return id(request_factory_reset);'
            then:
              - logger.log:
                  format: "Performing factory reset"
                  level: INFO
              - delay: 250ms
              - button.press: button_factory_reset
        - if:
            condition:
              all:
                - lambda: 'return id(request_restart);'
                - lambda: 'return !id(request_factory_reset);'
            then:
              - logger.log:
                  format: "Restarting"
                  level: INFO
              - delay: 250ms
              - button.press: button_restart
    on_multi_click: 
      - timing:
        - "ON for at most 1s"
        - "OFF for at least 0.3s"
        then:
          - logger.log:
              format: "Single clicked, toggling ${outlet_1_name}"
              level: INFO
          - switch.toggle: outlet1
      - timing:
        - "ON for at most 1s"
        - "OFF for at most 0.3s"
        - "ON for at most 1s"
        - "OFF for at least 0.3s"
        then:
          - logger.log:
              format: "Double clicked, toggling ${outlet_2_name}"
              level: INFO
          - switch.toggle: outlet2
      - timing:
        - "ON for at most 1s"
        - "OFF for at most 0.3s"
        - "ON for at most 1s"
        - "OFF for at most 0.3s"
        - "ON for at most 1s"
        - "OFF for at least 0.3s"
        then:
          - logger.log:
              format: "Triple clicked, toggling ${outlet_3_name}"
              level: INFO
          - switch.toggle: outlet3
      - timing:
        - "ON for at least 5s"
        then:
          - light.turn_on:
              id: light_status
              effect: "Slow Blink"
          - globals.set: 
              id: request_restart
              value: "true"
      - timing:
        - "ON for at least 10s"
        then:
          - light.turn_on:
              id: light_status
              effect: "Fast Blink"
          - globals.set: 
              id: request_factory_reset
              value: "true"

globals:
  - id: request_restart
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: request_factory_reset
    type: bool
    restore_value: no
    initial_value: 'false'

light:
  - platform: status_led
    id: light_status
    name: "Status Light"
    pin: TX1
    effects:
      - strobe:
          name: "Slow Blink"
          colors:
            - state: true
              duration: 250ms
            - state: false
              duration: 250ms
      - strobe:
          name: "Fast Blink"
          colors:
            - state: true
              duration: 100ms
            - state: false
              duration: 100ms

button:
  - platform: restart
    id: button_restart
    name: "Restart"
  
  - platform: factory_reset
    id: button_factory_reset
    name: Factory Reset